services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: depot
      POSTGRES_PASSWORD: depot
      POSTGRES_DB: depot_development
    ports:
      - "5432:5432"
    volumes:
      - depot_pg_data:/var/lib/postgresql/data

volumes:
  depot_pg_data:
